
name: Release Workflow

on:
  release:
    types: [released]
    tags:
      - 'v*'

env:
  EXECUTABLE_JAR: "cometTPP2LimelightXML.jar"
  DOCKER_REPO: "mriffle/comet-tpp-to-limelight"
  LIMELIGHT_RELEASE_TAG: ${{ github.event.release.tag_name }}

jobs:
  dockerhub:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Gradle
        run: ./gradlew shadowJar
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Get the version
        id: get_version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_OUTPUT
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_REPO }}:latest, ${{ env.DOCKER_REPO }}:${{ steps.get_version.outputs.VERSION }}

  release:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew shadowJar
      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/libs/${{ env.EXECUTABLE_JAR }}
          asset_name: ${{ env.EXECUTABLE_JAR }}
          tag: ${{ github.ref }}
          overwrite: true
          body: ""
